// Generated by CoffeeScript 1.7.1
angular.module('explore', []).controller('Eqns', function($scope) {
  $scope.x1 = -1;
  $scope.y1 = 2;
  $scope.z1 = 8;
  $scope.x2 = -2;
  $scope.y2 = 1;
  return $scope.z2 = -2;
});
